In [8]:
import pandas as pd

In [9]:
data=pd.DataFrame({"text":["people watch ineuron", "ineuron watch ineuron", "people write comment", "ineuron write ineuron"],"output":[1,1,0,0]})

In [10]:
data.head()

text  output
0   people watch ineuron       1
1  ineuron watch ineuron       1
2   people write comment       0
3  ineuron write ineuron       0

In [11]:
from sklearn.feature_extraction.text import CountVectorizer
BOW=CountVectorizer()

In [12]:
document_matrix=BOW.fit_transform(data["text"])
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [13]:
BOW.vocabulary_

{'people': 2, 'watch': 3, 'ineuron': 1, 'write': 4, 'comment': 0}

In [14]:
document_matrix[0].toarray()

array([[0, 1, 1, 1, 0]], dtype=int64)

In [15]:
document_matrix[1].toarray()

array([[0, 2, 0, 1, 0]], dtype=int64)

In [19]:
document_matrix[2].toarray()

array([[1, 0, 1, 0, 1]], dtype=int64)

In [20]:
document_matrix[3].toarray()

array([[0, 2, 0, 0, 1]], dtype=int64)

In [22]:
bigram=CountVectorizer(ngram_range=(2,2))
bigramvocab=bigram.fit_transform(data["text"])
bigram.vocabulary_

{'people watch': 2,
 'watch ineuron': 4,
 'ineuron watch': 0,
 'people write': 3,
 'write comment': 5,
 'ineuron write': 1,
 'write ineuron': 6}

In [23]:
trigram=CountVectorizer(ngram_range=(3,3))
trigramvocab=trigram.fit_transform(data["text"])
trigram.vocabulary_

{'people watch ineuron': 2,
 'ineuron watch ineuron': 0,
 'people write comment': 3,
 'ineuron write ineuron': 1}

In [25]:
mix=CountVectorizer(ngram_range=(1,2))
mixvocab=mix.fit_transform(data["text"])
mix.vocabulary_

{'people': 4,
 'watch': 7,
 'ineuron': 1,
 'people watch': 5,
 'watch ineuron': 8,
 'ineuron watch': 2,
 'write': 9,
 'comment': 0,
 'people write': 6,
 'write comment': 10,
 'ineuron write': 3,
 'write ineuron': 11}

In [29]:
#from sklearn.feature_extraction.text import TFidfVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer


In [30]:
tfidf=TfidfVectorizer()

In [31]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.66767854, 0.        , 0.52640543, 0.        , 0.52640543],
       [0.        , 0.8508161 , 0.        , 0.        , 0.52546357]])

In [34]:
tfidf.get_feature_names_out()

array(['comment', 'ineuron', 'people', 'watch', 'write'], dtype=object)

In [35]:
tfidf.idf_

array([1.91629073, 1.22314355, 1.51082562, 1.51082562, 1.51082562])